services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  postgres:
    container_name: postgres
    image: postgres
    environment:
      BUILD_ENV: docker
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5332:5432"
    networks:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "su -c 'pg_isready -U ${POSTGRES_USER} -h localhost' postgres -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:
  redis_data:
    driver: local

