CREATE TABLE PLANT_SPECIES(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(1000),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE HOUSEHOLD
(
    ID         uuid PRIMARY KEY,
    NAME       VARCHAR(1000) NOT NULL,
    ADDRESS    VARCHAR(1000) NOT NULL,
    PHONE_NUMBER VARCHAR(1000) NOT NULL,
    EMAIL      VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE OWNER(
    ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(1000),
    LAST_NAME VARCHAR(1000),
    HOUSEHOLD_ID INTEGER REFERENCES HOUSEHOLD(ID),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE PLANT(
    ID uuid PRIMARY KEY,
    PLANT_NAME VARCHAR(1000),
    PLANT_SPECIES_ID INTEGER REFERENCES PLANT_SPECIES(ID),
    OWNER_ID INTEGER REFERENCES OWNER(ID),
    HOUSEHOLD_ID INTEGER REFERENCES HOUSEHOLD(ID),
    PURCHASE_TIMESTAMP TIMESTAMP,
    PLANTING_TIMESTAMP TIMESTAMP,
    PLANT_STATUS VARCHAR(1000),
    NOTES_TXT VARCHAR(1000),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);