CREATE TABLE HOUSEHOLD
(
    ID         uuid PRIMARY KEY,
    NAME       VARCHAR(1000) NOT NULL,
    ADDRESS    VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE COLLECTIONS
(
    ID uuid PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    HOUSEHOLD_ID uuid REFERENCES HOUSEHOLD(ID),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);


CREATE TABLE OWNER (
    ID uuid PRIMARY KEY,
    FIRST_NAME VARCHAR(1000) NOT NULL,
    LAST_NAME VARCHAR(1000) NOT NULL,
    HOUSEHOLD_ID uuid REFERENCES HOUSEHOLD(ID),
    PHONE_NUMBER VARCHAR(1000) NOT NULL,
    EMAIL VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE PLANT(
    ID uuid PRIMARY KEY,
    PLANT_NAME VARCHAR(1000) NOT NULL,
    NICKNAME VARCHAR(1000),
    ORIGIN VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    OWNER_ID uuid REFERENCES OWNER(ID) NOT NULL,
    PURCHASE_TIMESTAMP TIMESTAMP NOT NULL,
    PLANTING_TIMESTAMP TIMESTAMP NOT NULL,
    PLANT_STATUS VARCHAR(1000) NOT NULL,
    NOTES_TXT VARCHAR(1000),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);